"""create user table

Revision ID: 26b4ec21cd5d
Revises: 
Create Date: 2021-11-14 14:40:30.568007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b4ec21cd5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('user_account_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_account_image')
    op.drop_column('users', 'user_bio')
    # ### end Alembic commands ###
