"""create comments table with relationship to posts table.

Revision ID: 7a4af54e8284
Revises: 9fb35430921b
Create Date: 2021-11-15 08:22:43.570412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4af54e8284'
down_revision = '9fb35430921b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_title', sa.String(length=60), nullable=False),
    sa.Column('comment_author', sa.String(length=60), nullable=False),
    sa.Column('comment_content', sa.Text(), nullable=False),
    sa.Column('comment_creation', sa.DateTime(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
