"""create posts    #user_posts= db.relationship('Post',backref='author',lazy=True) table

Revision ID: 9fb35430921b
Revises: 26b4ec21cd5d
Create Date: 2021-11-14 16:58:13.829611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb35430921b'
down_revision = '26b4ec21cd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=60), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('post_creation', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
